name: Trigger auto deployment for container-app-bmuof6eknbz3u

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-bmuof6eknbz3u-AutoDeployTrigger-08c26c49-1119-48f9-b8b5-ae13cf6504db.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPBMUOF6EKNBZ3U_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPBMUOF6EKNBZ3U_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPBMUOF6EKNBZ3U_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPBMUOF6EKNBZ3U_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPBMUOF6EKNBZ3U_REGISTRY_PASSWORD }}
          containerAppName: container-app-bmuof6eknbz3u
          resourceGroup: expresssample897bhh9c0e
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


